app/config/routes.rb
Rails.application.routes.draw do

  get "/sign_up_option", to: "pages#show", as: "show_page"
  get "/sign_in_option", to: "pages#signin", as: "sign_in_option"

  resources :pictures
  resources :cats do
    collection do
      get 'search'
      get 'present'
    end
    member do
      put "like", to: "cats#upvote"
      put "dislike", to: "cats#downvote"
    end
    resources :pictures, except: [:show, :index]
    resources :comments, except: [:index]
  end
  resources :comments
  devise_for :users
  devise_for :shelters
  resources :shelters, only: [:index]
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  get '/dashboard', to: 'dashboard#show', as: "show_dashboard"
  get '/homepage', to: 'homepage#show', as: "show_homepage"
  get '/userdashboard', to: 'userdashboard#show', as: "show_userdashboard"
  
  resources :shelters
  authenticated :user do
    root :to => "cats#index", :as => :authenticated_user_root
  end
  authenticated :shelter do
    root :to => "dashboard#show", :as => :authenticated_shelter_root
  end
  root to: "pages#signin"

end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daily Kitten</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand">Daily Kitten</div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if shelter_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= form_tag search_cats_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
              </li>
              <li><%= link_to 'Account', edit_shelter_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_shelter_session_path, :method => :delete %></li>
            </ul>
                <% end %>
          <% elsif user_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= form_tag search_cats_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
              </li>
              <li><%= link_to 'Account', show_userdashboard_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
                <% end %>
          <% else -%>
            <ul class="nav navbar-nav pull-right">
              <li>
                <%= form_tag search_cats_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
                <% end %>
              </li>
              <li><%= link_to 'Sign up', show_page_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
          <% end -%>
        </nav>
      </div>
    </div>
  </header>

  <div id="main_content" class="container">
    <!--<% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>-->

    <div id="content" class="col-md-10 center-block">
      <%= yield %>
    </div>

  </div>

</body>
</html>

app/app/views/layouts/cat_pins.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daily Kitten</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand">Daily Kitten</div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if shelter_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= form_tag search_cats_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
              </li>
              <li><%= link_to 'Account', edit_shelter_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_shelter_session_path, :method => :delete %></li>
            </ul>
                <% end %>
          <% elsif user_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= form_tag search_cats_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
              </li>
              <li><%= link_to 'Account', show_userdashboard_path %></li>
              <li><%= link_to 'Sign out', destroy_shelter_session_path, :method => :delete %></li>
            </ul>
                <% end %>
          <% else -%>
            <ul class="nav navbar-nav pull-right">
              <li>
                <%= form_tag search_cats_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
                <% end %>
              </li>
              <li><%= link_to 'Sign up', show_page_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
          <% end -%>
        </nav>
      </div>
    </div>
  </header>

  <%= yield %>

  </div>

</body>
</html>

app/app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daily Kitten</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
  <header class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand">Daily Kitten</div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= form_tag search_cats_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
                <% end %>
              </li>
              <li><%= link_to 'Account', edit_shelter_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_shelter_session_path, :method => :delete %></li>
            </ul>
        </nav>
      </div>
    </div>
  </header>

  <div id="wrapper">
    <%= yield %>
  </div>
</body>
</html>

app/app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daily Kitten</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>

</head>
<style>
video {
position: fixed;
top: 50%;
left: 50%;
min-width: 100%;
min-height: 100%;
width: auto;
height: auto;
z-index: -100;
-webkit-transform: translateX(-50%) translateY(-50%);
transform: translateX(-50%) translateY(-50%);
background: url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/polina.jpg') no-repeat; background-size: cover;  -webkit-transition: 1s opacity; transition: 1s opacity; }

</style>
</head>
<body>
<video autoplay="" loop="" id="bgvid" class="" controls muted>
<source src="<%= asset_path("cat.webm") %>" type="video/webm">
<source src="<%= asset_path("cat.mp4") %>" type="video/mp4">
<source src="<%= asset_path("cat.ogv") %>" type="video/ogg">
</video>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="wrap">
                <%= yield %>
            </div>
        </div>
    </div>
</div>

</body></html>

app/app/views/layouts/userdashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daily Kitten</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
  <header class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand">Daily Kitten</div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav pull-right">
              <li>
                <%= form_tag search_cats_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
                <% end %>
              </li>
              <li><%= link_to 'Account', show_userdashboard_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
        </nav>
      </div>
    </div>
  </header>

  <div id="wrapper">
    <%= yield %>
  </div>
</body>
</html>