app/config/routes.rb
Rails.application.routes.draw do

  get "/sign_up_option", to: "pages#show", as: "show_page"
  get "/sign_in_option", to: "pages#signin", as: "sign_in_option"

  resources :pictures
  resources :cats do
    collection do
      get 'search'
      get 'present'
    end
    member do
      put "like", to: "cats#upvote"
      put "dislike", to: "cats#downvote"
    end
    resources :pictures, except: [:show, :index]
    resources :comments, except: [:index]
  end
  resources :comments
  devise_for :users
  devise_for :shelters
  resources :shelters, only: [:index]
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  get '/dashboard', to: 'dashboard#show', as: "show_dashboard"
  get '/homepage', to: 'homepage#show', as: "show_homepage"
  get '/userdashboard', to: 'userdashboard#show', as: "show_userdashboard"
  
  resources :shelters
  authenticated :user do
    root :to => "cats#index", :as => :authenticated_user_root
  end
  authenticated :shelter do
    root :to => "dashboard#show", :as => :authenticated_shelter_root
  end
  root to: "pages#signin"

end

app/app/models/cat.rb
class Cat < ActiveRecord::Base
  searchkick
  extend Enumerize
  enumerize :sex, in: [:male, :female]
  enumerize :breed, in: [:abyssinian, :american_bobtail, :american_curl, :american_shorthair, :american_wirehair,
    :balinese, :bengal_cats, :birman, :bombay, :british_shorthair, :burmese, :burmilla,
    :chartreux, :chinese_li_hua, :colorpoint, :chorthair, :cornish_rex, :cymric,
    :devon_rex,
    :egyptian_mau, :european_burmese, :exotic,
    :havana_brown, :himalayan,
    :japanese_bobtail, :javanese,
    :korat,
    :laPerm,
    :maine_coon, :manx,
    :nebelung, :norwegian_forest,
    :ocicat, :others, :oriental,
    :persian,
    :ragamuffin, :ragdoll_cats, :russian_blue,
    :savannah, :scottish_fold, :selkirk_rex, :siamese_cat, :siberian, :singapura, :snowshoe, :somali, :sphynx,
    :tonkinese, :turkish_angora, :turkish_van]
  validates :age, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 30 }
  acts_as_votable
  has_many :comments
  has_many :pictures, :dependent => :destroy
  belongs_to :shelter
end

app/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user!, except: [:index, :show]
  before_filter :authenticate_shelter!, except: [:index, :show]
  layout 'cat_pins', only: [:index]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  def search
    if params[:search].present?
      @cats = Cat.search(params[:search])
    else
      @cats = Cat.all
    end
  end

  def present
    @cats = current_shelter.cats.all
  end

  # GET /cats/1
  # GET /cats/1.json
  
  def show
    if shelter_signed_in?
      @shelter = current_shelter
    else
      @shelter = @cat.shelter
    end
    @pictures = @cat.pictures
  end

  # GET /cats/new
  def new
    @shelter = current_shelter
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
    current_shelter.cats.find(params[:id])
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = current_shelter.cats.new(cat_params)
    @cat.shelter = current_shelter

    respond_to do |format|
      if @cat.save
        if params[:images]
          params[:images].each { |image|
            @cat.pictures.create(image: image)
          }
        end
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        if params[:images]
          params[:images].each { |image|
            @cat.pictures.create(image: image)
          }
        end
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat = current_shelter.cats.find(params[:id])
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to show_dashboard_path, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @cat = Cat.find(params[:id])
    @cat.upvote_by current_user
      redirect_to :back
  end

  def downvote
    @cat = Cat.find(params[:id])
    @cat.downvote_by current_user
      redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :age, :breed, :sex, :description, :pictures)
    end
end

app/app/helpers/cats_helper.rb
module CatsHelper
end

app/app/views/cats/_form.html.erb
<%= simple_form_for @cat, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control", placeholder:"Name" %>
    </div>
    <div class="form-group">
      <%= f.label :age %><br>
      <%= f.number_field :age, class: "form-control", placeholder:"Age" %>
    </div>
    <div class="form-group">
      <%= f.input :sex %>
    </div>
    <div class="form-group">
      <%= f.input :breed %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <label>Upload Cat Images</label>
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/app/views/cats/index.html.haml
#cats.transitions-enabled
  - @cats.each do |cat|
    - cat.pictures.each do |pic|
      .box.panel.panel-default
        = link_to (image_tag(pic.image.url(:origin))), cat
        %h2= link_to cat.name, cat
        %p.user
          =cat.description

app/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/app/views/cats/present.erb
<div class="row">
  <% @cats.each do |cat| %>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <% if cat.pictures.first %>
        <%= link_to image_tag(cat.pictures.first.image.url(:medium, :class => 'img-responsive')), cat_path(cat), class: "thumbnail" %>
      <% else %>
        N/A
      <% end %>
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <td><strong>Name:</strong></td>
              <td><%= cat.name %></td>
            </tr>
            <tr>
              <td><strong>Description:</strong></td>
              <td><%= cat.description %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/app/views/cats/search.html.erb
<div class="row">
  <% @cats.each do |cat| %>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <% if cat.pictures.first %>
        <%= link_to image_tag(cat.pictures.first.image.url(:medium, :class => 'img-responsive')), cat_path(cat), class: "thumbnail" %>
      <% else %>
        N/A
      <% end %>
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <td><strong>Name:</strong></td>
              <td><%= cat.name %></td>
            </tr>
            <tr>
              <td><strong>Description:</strong></td>
              <td><%= cat.description %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/app/views/cats/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-8">

        <div id="owl">
          <% unless @pictures.empty? %>
            <% @pictures.each do |pic| %>
              <div class="item center-block">
                <%= image_tag pic.image.url(:medium), class: "thumbnail" %>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="btn-group" style="padding-bottom: 20px;  padding-top: 20px;">
          <%= link_to like_cat_path(@cat), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
            Upvote
            <%= @cat.get_upvotes.size %>
          <% end %>
          <%= link_to dislike_cat_path(@cat), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-down">
            Downvote
            <%= @cat.get_downvotes.size %>
          <% end %>
        </div>

        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Name:</strong></td>
                <td><%= @cat.name %></td>
              </tr>
              <tr>
                <td><strong>Age:</strong></td>
                <td><%= @cat.age %></td>
              </tr>
              <tr>
                <td><strong>Breed:</strong></td>
                <td><%= @cat.breed.humanize %></td>
              </tr>
              <tr>
                <td><strong>Sex:</strong></td>
                <td><%= @cat.sex %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @cat.description %></td>
              </tr>
              
              <% if user_signed_in? %>
              <tr>
                <td><strong>Location: </strong></td>
                <td><%= @shelter.street_number %>, <%= @shelter.city %>, <%= @shelter.state %>, <%= @shelter.zipcode %></td>
              </tr>
              <tr>
                <td><strong>Contact Shelter!</strong></td>
                <td><%= link_to @shelter.name, @shelter.phone_number %></td>
              </tr>
              <tr>
                <td><strong>Distance</strong></td>
                <td><%= @user.zipcode %></td>
              <%= link_to "Send an Application", :root, class: "btn btn-primary" %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <h3 class="comments_title">
          <%= @cat.comments.count %> Comments
        </h3>

        <div id="comments">
          <%= render :partial => @cat.comments %>
        </div>
        <%= simple_form_for [@cat, Comment.new]  do |f| %>
          <div class="field">
            <%= f.text_area :body, class: "form-control" %>
          </div>
          <br>
          <%= f.submit "Add Comment", class: "btn btn-primary" %>
        <% end %>
        <% if shelter_signed_in? %>
        <%= link_to "Back", :show_dashboard, class: "btn btn-primary" %>
        <% elsif user_signed_in? %>
        <%= link_to "Back", :root, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){
 $('#owl').owlCarousel({
      autoPlay: 3000, //Set AutoPlay to 3 seconds

      items : 2,
      itemsDesktop : [1199,3],
      itemsDesktopSmall : [979,3]
 });
});
</script>