app/config/routes.rb
Rails.application.routes.draw do

  get "/sign_up_option", to: "pages#show", as: "show_page"
  get "/sign_in_option", to: "pages#signin", as: "sign_in_option"

  resources :pictures
  resources :cats do
    collection do
      get 'search'
      get 'present'
    end
    member do
      put "like", to: "cats#upvote"
      put "dislike", to: "cats#downvote"
    end
    resources :pictures, except: [:show, :index]
    resources :comments, except: [:index]
  end
  resources :comments
  devise_for :users
  devise_for :shelters
  resources :shelters, only: [:index]
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  get '/dashboard', to: 'dashboard#show', as: "show_dashboard"
  get '/homepage', to: 'homepage#show', as: "show_homepage"
  get '/userdashboard', to: 'userdashboard#show', as: "show_userdashboard"
  
  resources :shelters
  authenticated :user do
    root :to => "cats#index", :as => :authenticated_user_root
  end
  authenticated :shelter do
    root :to => "dashboard#show", :as => :authenticated_shelter_root
  end
  root to: "pages#signin"

end

app/app/models/link.rb
class Link < ActiveRecord::Base
    acts_as_votable
    has_many :comments
end

app/app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
      redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
      redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/app/helpers/links_helper.rb
module LinksHelper
end

app/app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/app/views/links/index.html.erb
<div class="row">
  <% @links.each do |link| %>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <%= link_to image_tag(link.url, :class => 'img-responsive'), link, class: "thumbnail"%>

      <div class="btn-group" style="padding-bottom: 10px;  padding-left: 10px;">
        <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-up"></span>
          Upvote
          <%= link.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down"></span>
          Downvote
          <%= link.get_downvotes.size %>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

app/app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/app/views/links/show.html.erb
<div class="page-header">
  <h1><a href="<%= @link.url %>"><%= @link.title %></a><br>
</div>

<div class="page-header">
  <div class="container">
    <div class="col-md-8" style="padding-left: 0px;  padding-right: 0px;">
      <img src="<%= @link.url %>" class="img-responsive"></h1>
    </div>
  </div>
</div>

<div class="btn-group pull-right">
  <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-up"></span>
    Upvote
    <%= @link.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-down">
    Downvote
    <%= @link.get_downvotes.size %>
  <% end %>
</div>

<h3 class="comments_title">
  <%= @link.comments.count %> Comments
</h3>

<div id="comments">
  <%= render :partial => @link.comments %>
</div>
<%= simple_form_for [@link, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>